sudo: required

services:
  - docker

before_install:
  - docker run --detach --publish 27017:27017 --name mongo mvertes/alpine-mongo:3.2.10-3
  - sleep 10

language: node_js

node_js:
  - "8"
  - "10"
  - "12"

